openapi: 3.0.0
info:
  title: Custom Model Interaction API
  description: API for prompting a custom model and receiving responses.
  version: 1.0.0
servers:
  - url: http://159.2.191.208:5001/v1
    description: Main API server
paths:
  /promptCustomModel:
    post:
      operationId: promptCustomModel
      summary: Sends a prompt to the custom model.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The prompt to send to the custom model.
      responses:
        '202':
          description: Accepted. The request has been accepted for processing.
        '400':
          description: Bad request. The request was invalid or cannot be served.
  /modelResponse:
    get:
      operationId: getModelResponse
      summary: Receives the response from the custom model.
      responses:
        '200':
          description: OK. The response from the custom model.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The response from the custom model.
        '404':
          description: Not found. No response available yet.
